### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by aanchal-fatwani** [Devansh-Baghel/cv-app#1]
@Devansh-Baghel As part of HacktoberFest2023, I wish to update the ReadMe for this repository to present better information.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

**Comment by Devansh-Baghel** [comment]
@aanchal-fatwani i don't intend this repo to be a part of hacktoberfest, i have basically abandoned this project at this point.
